export const SUPABASE_URL = "https://vwqxoubutxhqdebhnwlg.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cXhvdWJ1dHhocWRlYmhud2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njg0MDUxNDAsImV4cCI6MTk4Mzk4MTE0MH0.FjTKlA7UM2XMzpff9jldMuHDy4HARvUwBe3RAU8Z6Mk";
